Repository jenkins-x/dex, pull requests merged in 2019-11, with the labels that each got.

#21 feat: add an openssl image with kubectl so the grpc job can replicate…
  Dockerfile.openssl
  charts/dex/templates/job-grpc-certs.yaml
  charts/dex/values.yaml
  jenkins-x.yml
Labels: approved, size/M

#22 feat: add cloudbees connector
  connector/cloudbees/oidc.go
  connector/cloudbees/oidc_test.go
  server/server.go
Labels: approved, size/L

#23 fix: reuse name field for cloudbees id
  connector/cloudbees/oidc.go
Labels: approved, size/XS
