Repository jenkins-x/dex, pull requests merged in 2019-03, with the labels that each got.

#9 don't use the login with email screen
  charts/dex/templates/_dex_config.yaml.tpl
Labels: approved, lgtm, size/XS

#10 Update owners file
  OWNERS
Labels: approved, lgtm, size/XS

#11 feat(login) use github logins not IDs as the underlying id
  charts/dex/templates/_dex_config.yaml.tpl
Labels: approved, size/XS

#12 Fix indention in the template
  charts/dex/templates/_dex_config.yaml.tpl
Labels: approved, size/XS

#13 update skaffold.yaml
  skaffold.yaml
Labels: approved, size/S
